"""
=============================================================================
SCRIPT NAME: strategic_planner.py
=============================================================================

Strategic Planner - Opus analyzes tasks and selects models.

INPUT FILES:
- Task description from user

OUTPUT FILES:
- ExecutionPlan with model selections and constraints

VERSION: 1.0
LAST UPDATED: 2025-11-26

DESCRIPTION:
Uses Claude Opus 4.5 to analyze tasks, classify problem archetypes,
decompose into features, and select appropriate models for each phase.

DEPENDENCIES:
- json (standard library)
- re (standard library)

=============================================================================
"""

import json
import re
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, field

from .model_registry import MODEL_REGISTRY, ModelConfig, get_model, get_model_menu
from .multi_provider_client import MultiProviderClient
from .feature_list import FeatureList, Feature
from .presets import VariantPreset


@dataclass
class ExecutionPlan:
    """Plan generated by Opus for task execution."""
    task_id: str
    archetype: str  # quick_fix, feature_build, architecture, haystack, concurrency
    complexity: str  # simple, medium, complex, expert
    domain: str  # algorithms, systems, data-structures, ml, etc.

    # Model selections
    context_model: str
    engineering_model: str
    review_model: str
    default_engineering_model: str  # For features without specific assignment

    # Selection rationale
    model_rationale: Dict[str, str] = field(default_factory=dict)

    # Constraints for agents (list of {level, description})
    global_constraints: List[Dict[str, str]] = field(default_factory=list)

    # Success criteria
    success_criteria: List[str] = field(default_factory=list)

    # Predicted issues
    predicted_failure_modes: List[str] = field(default_factory=list)


PLANNING_PROMPT = '''You are the Opus Meta-Orchestrator - the strategic brain of an autonomous coding system.
Your job is NOT to write code. It is to ANALYZE tasks and CREATE EXECUTION PLANS that maximize the probability of working, executable code.

===============================================================================
CRITICAL PRINCIPLE: EXECUTION > ELEGANCE
===============================================================================
Historical data shows:
- Over-engineered solutions: 20% execution rate
- Simple, focused solutions: 80% execution rate

Your job is to CONSTRAIN agents to produce WORKING code, not impressive code.

===============================================================================
AVAILABLE MODELS
===============================================================================
{model_menu}

===============================================================================
USER REQUEST
===============================================================================
{task}

===============================================================================
PHASE 1: PROBLEM ARCHETYPE CLASSIFICATION
===============================================================================

Classify into ONE archetype:

+---------------------+--------------------------------------------------------+
| ARCHETYPE           | STRATEGY                                               |
+---------------------+--------------------------------------------------------+
| "quick_fix"         | SPEED. Simple bug/typo. Use Cerebras/Groq fastest.    |
|                     | Models: qwen3-235b, glm-4.6, kimi-k2                   |
+---------------------+--------------------------------------------------------+
| "feature_build"     | BALANCE. New isolated functionality. Medium models.    |
|                     | Models: gpt-5.1, sonnet-4.5                            |
+---------------------+--------------------------------------------------------+
| "architecture"      | INTELLIGENCE. Core system changes. Premium models.     |
|                     | Models: opus-4.5, sonnet-4.5                           |
+---------------------+--------------------------------------------------------+
| "haystack"          | CONTEXT. Debug across many files. Large context.       |
|                     | Models: gemini-2.5-pro (1M context)                    |
+---------------------+--------------------------------------------------------+
| "concurrency"       | PRECISION. Thread-safety, race conditions. Careful.    |
|                     | Models: sonnet-4.5, gpt-5.1 + kimi-k2-thinking review  |
+---------------------+--------------------------------------------------------+

===============================================================================
PHASE 2: PROVIDER DIVERSIFICATION (Avoid Model Collapse)
===============================================================================

Use DIFFERENT providers for Engineering vs Review to avoid same biases:

Good combinations:
- Engineering: OpenAI (gpt-5.1) -> Review: Anthropic (sonnet-4.5)
- Engineering: Cerebras (qwen3-235b) -> Review: Groq (kimi-k2)
- Engineering: Anthropic (sonnet-4.5) -> Review: OpenAI or Groq

Bad combinations (same provider bias):
- Engineering: sonnet-4.5 -> Review: opus-4.5 (both Anthropic)
- Engineering: gpt-5.1 -> Review: gpt-5.1 (same model!)

===============================================================================
PHASE 3: CONSTRAINT ENGINEERING
===============================================================================

Generate constraints at THREE levels:

MUST (Violation = Automatic Rejection):
   - "Implement as single self-contained Python file"
   - "Use Python standard library only"
   - "Handle edge cases: empty input, None, type errors"

MUST_NOT (Violation = Automatic Rejection):
   - "Do NOT use external packages (requests, redis, pandas)"
   - "Do NOT create multiple files or modules"
   - "Do NOT create abstract base classes"
   - "Do NOT implement unrequested features"

SHOULD (Strong Recommendations):
   - "Prefer iterative over recursive"
   - "Include docstrings with complexity analysis"
   - "Use type hints for all parameters"

Add DOMAIN-SPECIFIC constraints based on archetype:

FOR "concurrency":
  MUST: "Use threading.Lock for all shared state"
  MUST: "Use context managers for lock acquisition"
  MUST_NOT: "Do NOT use global variables for shared state"

FOR "feature_build" with algorithms:
  MUST: "Include time/space complexity in docstring"
  SHOULD: "Handle empty/single-element edge cases explicitly"

===============================================================================
PHASE 4: FEATURE DECOMPOSITION (Anthropic Pattern)
===============================================================================

Break the task into INCREMENTAL FEATURES. Each feature should be:
- Small enough to implement in one pass
- Independently testable
- Building on previous features

CRITICAL: Do NOT try to implement everything at once.
"Incremental scope limitation prevents the failure mode where agents
attempt to one-shot the app, leading to incomplete implementations."

Example decomposition for "Thread-safe LRU Cache":
  F1: Basic get/put with O(1) lookup -> Simple, use fast model
  F2: LRU eviction on capacity -> Medium, may need better model
  F3: Thread safety with locks -> Complex, use premium model

Assign DIFFERENT MODELS to features based on complexity:
- Simple features -> qwen3-235b, glm-4.6 (fast)
- Medium features -> gpt-5.1 (balanced)
- Complex features -> sonnet-4.5 (careful)

===============================================================================
PHASE 5: FAILURE PREDICTION
===============================================================================

Predict what could go wrong and how constraints prevent it:

Common failures to predict:
- ImportError (external dependency) -> Constraint: stdlib only
- Multi-file import error -> Constraint: single file
- Race condition -> Constraint: Lock required
- Stack overflow -> Constraint: prefer iterative
- Half-implemented feature -> Constraint: clean state invariant

===============================================================================
OUTPUT FORMAT (JSON with Feature List)
===============================================================================

{{
  "archetype": "quick_fix|feature_build|architecture|haystack|concurrency",
  "complexity": "simple|medium|complex|expert",
  "domain": "algorithms|data-structures|systems|concurrency|web|ml|devops",

  "features": [
    {{
      "id": "F1",
      "description": "<what this feature does>",
      "tests": ["<test1>", "<test2>"],
      "constraints": ["<feature-specific constraint>"],
      "assigned_model": "<model for this feature>",
      "depends_on": []
    }},
    {{
      "id": "F2",
      "description": "<what this feature does>",
      "tests": ["<test1>", "<test2>"],
      "constraints": ["<feature-specific constraint>"],
      "assigned_model": "<model for this feature>",
      "depends_on": ["F1"]
    }}
  ],

  "model_selections": {{
    "context": {{
      "model": "<model_name>",
      "provider": "<cerebras|groq|openai|openrouter>",
      "rationale": "<specific reason>"
    }},
    "default_engineering": {{
      "model": "<default model if not specified per-feature>",
      "provider": "<provider>",
      "rationale": "<specific reason>"
    }},
    "review": {{
      "model": "<model_name>",
      "provider": "<different_provider - avoid model collapse>",
      "rationale": "<specific reason>"
    }}
  }},

  "global_constraints": {{
    "must": [
      {{"rule": "<constraint>", "validation": "<how to check>"}}
    ],
    "must_not": [
      {{"rule": "<forbidden action>", "violation_signal": "<what to look for>"}}
    ],
    "should": [
      {{"rule": "<recommendation>", "benefit": "<why>"}}
    ]
  }},

  "clean_state_invariant": {{
    "checks": [
      "No syntax errors",
      "No TODO/FIXME for critical functionality",
      "No placeholder implementations",
      "All features complete or not started (no half-done)"
    ]
  }},

  "failure_predictions": [
    {{
      "risk": "<what could fail>",
      "likelihood": "low|medium|high",
      "constraint_mitigation": "<which constraint prevents this>"
    }}
  ]
}}
'''


class StrategicPlanner:
    """Uses Opus to analyze tasks and create execution plans."""

    def __init__(
        self,
        client: MultiProviderClient,
        preset: Optional[VariantPreset] = None
    ):
        """
        Initialize the strategic planner.

        Args:
            client: Multi-provider client for API calls
            preset: Optional preset to constrain model selection
        """
        self.client = client
        self.preset = preset
        self.opus_config = get_model("opus-4.5")

    def create_plan(self, task: str, task_id: str = None) -> ExecutionPlan:
        """
        Analyze task and create execution plan.

        Args:
            task: Task description
            task_id: Optional task identifier

        Returns:
            ExecutionPlan with model selections and constraints
        """
        plan, _ = self.create_plan_with_features(task, task_id)
        return plan

    def create_plan_with_features(
        self,
        task: str,
        task_id: str = None
    ) -> Tuple[ExecutionPlan, FeatureList]:
        """
        Analyze task and create execution plan with feature list.

        Args:
            task: Task description
            task_id: Optional task identifier

        Returns:
            Tuple of (ExecutionPlan, FeatureList)
        """
        # Build model menu for prompt
        model_menu = self._format_model_menu()

        # Call Opus for planning
        messages = [
            {"role": "user", "content": PLANNING_PROMPT.format(
                model_menu=model_menu,
                task=task
            )}
        ]

        result = self.client.complete(
            model_config=self.opus_config,
            messages=messages,
            max_tokens=3000,
            temperature=0
        )

        # Parse response
        plan_data = self._parse_plan(result.content)

        # Apply preset constraints if specified
        if self.preset:
            plan_data = self._apply_preset_constraints(plan_data)

        # Build ExecutionPlan
        plan = ExecutionPlan(
            task_id=task_id or "task_001",
            archetype=plan_data.get("archetype", "feature_build"),
            complexity=plan_data.get("complexity", "medium"),
            domain=plan_data.get("domain", "general"),
            context_model=plan_data["model_selections"]["context"]["model"],
            engineering_model=plan_data["model_selections"].get(
                "default_engineering", plan_data["model_selections"]["context"]
            )["model"],
            review_model=plan_data["model_selections"]["review"]["model"],
            default_engineering_model=plan_data["model_selections"].get(
                "default_engineering", {}
            ).get("model", "qwen3-235b"),
            model_rationale={
                "context": plan_data["model_selections"]["context"]["rationale"],
                "engineering": plan_data["model_selections"].get(
                    "default_engineering", {}
                ).get("rationale", ""),
                "review": plan_data["model_selections"]["review"]["rationale"],
            },
            global_constraints=self._flatten_constraints(plan_data.get("global_constraints", {})),
            success_criteria=plan_data.get("clean_state_invariant", {}).get("checks", []),
            predicted_failure_modes=[
                f["risk"] for f in plan_data.get("failure_predictions", [])
            ]
        )

        # Build FeatureList
        feature_list = FeatureList(
            task_id=task_id or "task_001",
            task_description=task,
            features=[
                Feature(
                    id=f["id"],
                    description=f["description"],
                    tests=f.get("tests", []),
                    constraints=f.get("constraints", []),
                    assigned_model=f.get("assigned_model")
                )
                for f in plan_data.get("features", [])
            ],
            global_constraints=[c["description"] for c in plan.global_constraints]
        )

        return plan, feature_list

    def _format_model_menu(self) -> str:
        """Format model registry as menu for prompt."""
        if self.preset:
            # Only show allowed models
            lines = []
            for name in self.preset.allowed_models:
                if name in MODEL_REGISTRY:
                    config = MODEL_REGISTRY[name]
                    lines.append(
                        f"- {name}: {config.speed_tok_s} tok/s, "
                        f"${config.output_price_per_m}/M output, "
                        f"capabilities: {', '.join(config.capabilities)}"
                    )
            return "\n".join(lines)
        else:
            return get_model_menu()

    def _parse_plan(self, content: str) -> Dict:
        """Parse JSON from Opus response."""
        try:
            # Try direct parse
            return json.loads(content)
        except json.JSONDecodeError:
            # Try to find JSON in response
            match = re.search(r'\{[\s\S]*\}', content)
            if match:
                return json.loads(match.group())
            raise ValueError(f"Could not parse plan from response: {content[:500]}")

    def _apply_preset_constraints(self, plan_data: Dict) -> Dict:
        """Apply preset constraints to plan."""
        allowed = self.preset.allowed_models

        # Constrain model selections
        for role in ["context", "default_engineering", "review"]:
            if role in plan_data.get("model_selections", {}):
                selected = plan_data["model_selections"][role]["model"]
                if selected not in allowed:
                    # Fall back to preset default
                    if role == "context":
                        plan_data["model_selections"][role]["model"] = self.preset.default_context
                    elif role == "default_engineering":
                        plan_data["model_selections"][role]["model"] = self.preset.default_engineering
                    elif role == "review":
                        plan_data["model_selections"][role]["model"] = self.preset.default_review

        # Constrain feature model assignments
        for feature in plan_data.get("features", []):
            if feature.get("assigned_model") not in allowed:
                feature["assigned_model"] = self.preset.default_engineering

        return plan_data

    def _flatten_constraints(self, constraints_dict: Dict) -> List[Dict[str, str]]:
        """Flatten constraint structure into list."""
        result = []

        for level, items in constraints_dict.items():
            if isinstance(items, list):
                for item in items:
                    if isinstance(item, dict):
                        result.append({
                            "level": level.upper(),
                            "description": item.get("rule", str(item))
                        })
                    else:
                        result.append({
                            "level": level.upper(),
                            "description": str(item)
                        })

        return result
